[package]
name = "ghidra-auth"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"
license = "Zlib"

[dependencies]
serde = { version = "1.0.116", features = ["derive"] }
bincode = "1.3.1"
smol_str = { version = "0.1.17", features = ["serde"] }
scrypt = "0.5.0"
